### ISSUE TITLE
ci: add `dependabot` for terraform

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-basic#504]
Ref: https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/dependabot.yml
``` 
 - directory: "/infrastructure/repository"
    package-ecosystem: "terraform"
    schedule:
      interval: "daily"
```
